# Overall Training Parameters

seed: 255

batch_size: 18
epochs: 200

folds: 10
stratified: True

load_model: False
save_model: True

save_path: './save/'
syn_file_name: 'graph.pt'
final_file_name: 'final.pth'

optim: 'AdamW' # Adam, SGD, AdamW
sched: 'CosAnneal' # Step, Exp, CosAnneal, Reduce, OneCycle
step_size: 250
