# Overall Training Parameters

seed: 123

batch_size: 8
epochs: 100

folds: 10

load_model: False
save_model: True

save_path: './save/'
syn_file_name: 'graph.pt'

optim: 'Adam' # Adam, SGD, AdamW
sched: 'Step' # Step, Exp, CosAnneal, Reduce, OneCycle
