# Overall Training Parameters

seed: 123

batch_size: 18
epochs: 200

folds: 20
stratified: True

load_model: False
save_model: True

save_path: './save/'
syn_file_name: 'graph.pt'

optim: 'AdamW' # Adam, SGD, AdamW
sched: 'CosAnneal' # Step, Exp, CosAnneal, Reduce, OneCycle
step_size: 250
