# Default Configuration File Used By Hydra

defaults:
  - train: basic
  - dataset: word_judge
  - model: BrainGNN
  - log: log

project: 'WordJudge'
wandb_entity: 'outspace'

override_data: False

cuda: True
seed: 123

