# Default Configuration File Used By Hydra

defaults:
  - _self_
  - dataset: WordJudge
  - model: BrainGNN
  - train: Train
  - log: Log

project: 'WordJudge'
entity: 'outspace'
group: 'RRC_wRRC_'

cuda: True

hydra:
  run:
    dir: ./log/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
