# Model Parameters for BrainGNN

lr: 0.001

step_size: 20
momentum: 0.1
weight_decay: 5e-3

n_layer: 2
n_roi: 360
pool_ratio: 0.5
eps: 1e-10

in_dim: 360
out_dim: 6

lamb_subject: 0.1
lamb_group: 0.1
